config/routes.rb
Rails.application.routes.draw do
  root 'concerts#index'
  resources :concerts
  get 'concerts/:id/like', to: 'concerts#like'
  get 'popularConcerts', to: 'concerts#popularConcerts'
  get 'allConcerts', to: 'concerts#allConcerts'
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	validates :bandName, :venue, :city, :date, :price, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
	def index
		@concerts = Concert.all
	end

	def show
		@concerts = Concert.find(params[:id])
	end

	def new
		@concert = Concert.new
	end

	def create
		@concert = Concert.new(concert_params)

		@concerts = Concert.all
		if @concert.save
			redirect_to concerts_path
		else
			render action: 'new'
		end
	end

	def destroy
		@concert = Concert.find(params[:id])
		@concert.destroy
		redirect_to concerts_path
	end

	def like
		@concert = Concert.find(params[:id])
		@concert.update_attribute(:totalLikes, @concert.totalLikes + 1)
		redirect_to concert_path(@concert)
	end

	def popularConcerts
		@concerts = Concert.order(totalLikes: :desc)
	end

	def allConcerts
		@concerts = Concert.all
	end

	private
	def concert_params
		params.require(:concert).permit(:bandName, :venue, :city, :date, :price, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/allConcerts.html.erb
<nav class="nav primary-nav">
	<ul>
		<li><a><%= link_to 'Home', concerts_path %></a></li><!--
		--><li><a><%= link_to 'New concert', new_concert_path %></a></li><!--
		--><li><a><%= link_to 'Popular concerts', popularConcerts_path %></a></li><!--
		--><li><a><%= link_to 'All concerts', allConcerts_path %></a></li>
	</ul>
</nav>

<h1>All concerts</h1>

<% @concerts.each do |concert| %>
<div class="acceder-a-conciertos">
	<a><%= link_to concert.bandName, concert_path(concert) %></a>
		<%= concert.city %>,
		<%= concert.date %>
		<%= button_to 'Eliminar', concert_path(concert), method: :delete %>
</div>
<% end %>

<footer>Crafted with &hearts; by Alejo, Ivan, Irene y Juan Carlos</footer>

app/views/concerts/index.html.erb
<nav class="nav primary-nav">
	<ul>
		<li><a><%= link_to 'Home', concerts_path %></a></li><!--
		--><li><a><%= link_to 'New concert', new_concert_path %></a></li><!--
		--><li><a><%= link_to 'Popular concerts', popularConcerts_path %></a></li><!--
		--><li><a><%= link_to 'All concerts', allConcerts_path %></a></li>
	</ul>
</nav>

<% añoActual = Date.today.year %>
<% mesActual = Date.today.month %>
<% diaActual = Date.today.day %>

<% fechaActual = añoActual.to_s + mesActual.to_s + diaActual.to_s %>
<% fechaActualHastaMes = añoActual.to_s + mesActual.to_s %>

<div id="today-concerts">
	<h1>Today concerts</h1>
	
	<% @concerts.each do |concert| %>
	<div class="acceder-a-conciertos">
		<% añoConcierto = concert.date.to_s.slice(0..3) %>
		<% mesConcierto = concert.date.to_s.slice(5..6).sub(/^0/, "") %>
		<% diaConcierto = concert.date.to_s.slice(8..9).sub(/^0/, "") %>
		<% fechaConcierto = añoConcierto + mesConcierto + diaConcierto %>

		<% if fechaConcierto === fechaActual %>
			<a><%= link_to concert.bandName, concert_path(concert) %></a>
		<% end %>
	</div>
	<% end %>
</div>

<div id="month-concerts">
	<h1>This month...</h>

	<% @concerts.each do |concert| %>
	<div class="acceder-a-conciertos">
		<% añoConcierto = concert.date.to_s.slice(0..3) %>
		<% mesConcierto = concert.date.to_s.slice(5..6).sub(/^0/, "") %>
		<% fechaConciertoParaEsteMes = añoConcierto + mesConcierto %>

		<% if fechaConciertoParaEsteMes === fechaActualHastaMes %>
			<a><%= link_to concert.bandName, concert_path(concert) %></a>
		<% end %>
	</div>	
	<% end %>
	
</div>

<footer>
	<p id="info">Nuestra web es aprueba de hackers, pero conseguimos algo más dificil, que los likes se mantengan aunque recargues o cierres la página. No es asombroso!?!?!?</p>
	<p id="creators">Crafted with &hearts; by Alejo, Irene, Ivan y Juan Carlos</p>
</footer>

app/views/concerts/new.html.erb
<nav class="nav primary-nav">
	<ul>
		<li><a><%= link_to 'Home', concerts_path %></a></li><!--
		--><li><a><%= link_to 'New concert', new_concert_path %></a></li><!--
		--><li><a><%= link_to 'Popular concerts', popularConcerts_path %></a></li><!--
		--><li><a><%= link_to 'All concerts', allConcerts_path %></a></li>
	</ul>
</nav>

<% if @concert.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @concert.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @concert do |f| %>
<p>
	<%= f.label :bandName %><br>
	<%= f.text_field :bandName %>
</p>

<p>
	<%= f.label :venue %><br>
	<%= f.text_field :venue %>
</p>

<p>
	<%= f.label :city %><br>
	<%= f.text_field :city %>
</p>

<p>
	<%= f.label :date %><br>
	<%= f.text_field :date, :id=>'fecha', :placeholder => 'YYYY-MM-DD' %>
</p>

<p>
	<%= f.label :price %><br>
	<%= f.text_field :price %>
</p>

<p>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

<footer>Crafted with &hearts; by Alejo, Ivan, Irene y Juan Carlos</footer>

app/views/concerts/popularConcerts.html.erb
<nav class="nav primary-nav">
	<ul>
		<li><a><%= link_to 'Home', concerts_path %></a></li><!--
		--><li><a><%= link_to 'New concert', new_concert_path %></a></li><!--
		--><li><a><%= link_to 'Popular concerts', popularConcerts_path %></a></li><!--
		--><li><a><%= link_to 'All concerts', allConcerts_path %></a></li>
	</ul>
</nav>

<h1>Popular concerts</h1>

<h2>(Ordered by likes)</h2>

<% @concerts.each do |concert| %>
<div class="acceder-a-conciertos">
<a><%= link_to concert.bandName, concert_path(concert) %></a> <%= concert.totalLikes %> likes
</div>
<% end %>

<footer>Crafted with &hearts; by Alejo, Ivan, Irene y Juan Carlos</footer>

app/views/concerts/show.html.erb
<nav class="nav primary-nav">
	<ul>
		<li><a><%= link_to 'Home', concerts_path %></a></li><!--
		--><li><a><%= link_to 'New concert', new_concert_path %></a></li><!--
		--><li><a><%= link_to 'Popular concerts', popularConcerts_path %></a></li><!--
		--><li><a><%= link_to 'All concerts', allConcerts_path %></a></li>
	</ul>
</nav>

<h1 id="band"><%= @concerts.bandName %></h1>

<div>
<div id="datosConcierto">
	<span class="textInfo"><span class="label">Date: </span><%=@concerts.date %></span>
	<span class="textInfo"><span class="label">City: </span><%= @concerts.city %></span>
	<span class="textInfo"><span class="label">Venue: </span><%= @concerts.venue %></span>
	<span class="textInfo"><span class="label">Price: </span><%= @concerts.price %></span>
</div>

<div id="description">
	<%= @concerts.description %>
</div>

<div id="likeButton"><a><%= link_to '¡Danos un like!', :controller => 'concerts', :action => 'like' %></a></div><br><br> tenemos <%= @concerts.totalLikes %>

<footer>Crafted with &hearts; by Alejo, Ivan, Irene y Juan Carlos</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ConcertPlatform</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
  	<%= javascript_include_tag 'default' %>
  	<%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>